# -*- coding: utf-8 -*-
"""
/***************************************************************************
 derogationDialog
                                 A QGIS plugin
 Ce plugin est compose de 2 parties : La premiere partie concerne l'implementation des bidonvilles, il aide ainsi a faciliter la prise de decision pour faire la derogation.  La deuxieme partie consiste a automatiser le telechargement et le traitement des images Sentinel-1.  
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-22
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Abdellaoui Houda- Laghrissi Chafik
        email                : abdellaouihouda2@gmail,com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'derogation_processing_dialog_base.ui'))


class derogationDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(derogationDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
